In [1]:
import torch

In [47]:
a = torch.tensor([1.], requires_grad=True)
b = torch.tensor([3.], requires_grad=True)

In [48]:
a

tensor([1.], requires_grad=True)

In [49]:
y = a**2 - b**3
y

tensor([-26.], grad_fn=<SubBackward0>)

In [50]:
# gradient = derivative
# dy/da = 2a = 2
# dy/db = -3b^2 = -3 * 3^2 = -27

In [51]:
y.backward()

In [52]:
a.grad

tensor([2.])

In [53]:
b.grad

tensor([-27.])

In [54]:
features = torch.rand(1, 10)
weights = torch.rand(10, 1, requires_grad=True)
bias = torch.rand(1, requires_grad=True)

In [55]:
output = torch.matmul(features, weights) + bias
loss = 1 - output

In [56]:
output

tensor([[3.2918]], grad_fn=<AddBackward0>)

In [57]:
loss.backward()

In [58]:
weights.grad

tensor([[-0.4247],
        [-0.7346],
        [-0.0517],
        [-0.4072],
        [-0.9574],
        [-0.0127],
        [-0.4201],
        [-0.7855],
        [-0.8338],
        [-0.8283]])

In [59]:
bias.grad

tensor([-1.])

In [60]:
with torch.no_grad():
    weights = weights - (0.01 * weights.grad)

In [61]:
weights

tensor([[0.3725],
        [0.8160],
        [0.1704],
        [0.7526],
        [0.0543],
        [0.1282],
        [0.7431],
        [0.0636],
        [0.6305],
        [0.7284]])