In [1]:
import numpy as np
import torch

In [8]:
torch.cuda.is_available()

False

In [9]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


In [3]:
a = [[4,3], [1,2]]
type(a)

list

In [5]:
a

[[4, 3], [1, 2]]

In [4]:
a_np = np.asarray(a)
a_np

array([[4, 3],
       [1, 2]])

In [10]:
a_torch = torch.tensor(a)
a_torch

tensor([[4, 3],
        [1, 2]])

In [11]:
type(a_torch)

torch.Tensor

In [12]:
a_torch.dtype

torch.int64

In [15]:
np_array = np.random.rand(2,3)
np_array

array([[0.02876857, 0.13585852, 0.84163006],
       [0.69012832, 0.89342652, 0.43631069]])

In [16]:
tensor_np = torch.tensor(np_array)
tensor_np

tensor([[0.0288, 0.1359, 0.8416],
        [0.6901, 0.8934, 0.4363]], dtype=torch.float64)

In [18]:
torch.ones(2,4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [19]:
torch.zeros(1,5)

tensor([[0., 0., 0., 0., 0.]])

In [17]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.0503, 0.5109, 0.7314, 0.6395],
        [0.3917, 0.4209, 0.9686, 0.7632],
        [0.8504, 0.5648, 0.7668, 0.7648]])

In [21]:
random_tensor.device

device(type='cpu')

In [22]:
random_tensor[1:, :]

tensor([[0.3917, 0.4209, 0.9686, 0.7632],
        [0.8504, 0.5648, 0.7668, 0.7648]])

In [23]:
random_tensor.mul(random_tensor)

tensor([[0.0025, 0.2610, 0.5349, 0.4089],
        [0.1535, 0.1772, 0.9381, 0.5824],
        [0.7232, 0.3190, 0.5879, 0.5849]])

In [24]:
random_tensor * random_tensor

tensor([[0.0025, 0.2610, 0.5349, 0.4089],
        [0.1535, 0.1772, 0.9381, 0.5824],
        [0.7232, 0.3190, 0.5879, 0.5849]])

In [27]:
random_tensor.matmul(random_tensor.T)

tensor([[1.2073, 1.4311, 1.3812],
        [1.4311, 1.8512, 1.8972],
        [1.3812, 1.8972, 2.2151]])

In [28]:
torch.matmul(random_tensor, random_tensor.T)

tensor([[1.2073, 1.4311, 1.3812],
        [1.4311, 1.8512, 1.8972],
        [1.3812, 1.8972, 2.2151]])

In [29]:
random_tensor.sum(axis=0) #_ sum across the columns

tensor([1.2925, 1.4966, 2.4667, 2.1674])

In [30]:
torch.cat([random_tensor, random_tensor]) #_concatenate along the rows

tensor([[0.0503, 0.5109, 0.7314, 0.6395],
        [0.3917, 0.4209, 0.9686, 0.7632],
        [0.8504, 0.5648, 0.7668, 0.7648],
        [0.0503, 0.5109, 0.7314, 0.6395],
        [0.3917, 0.4209, 0.9686, 0.7632],
        [0.8504, 0.5648, 0.7668, 0.7648]])

In [31]:
torch.cat([random_tensor, random_tensor], axis=1) #_concatenate along the columns

tensor([[0.0503, 0.5109, 0.7314, 0.6395, 0.0503, 0.5109, 0.7314, 0.6395],
        [0.3917, 0.4209, 0.9686, 0.7632, 0.3917, 0.4209, 0.9686, 0.7632],
        [0.8504, 0.5648, 0.7668, 0.7648, 0.8504, 0.5648, 0.7668, 0.7648]])

In [33]:
torch.nn.functional.softmax(random_tensor, dim=1)

tensor([[0.1572, 0.2491, 0.3105, 0.2833],
        [0.1901, 0.1957, 0.3385, 0.2756],
        [0.2786, 0.2094, 0.2563, 0.2557]])

In [34]:
random_tensor.shape

torch.Size([3, 4])

In [35]:
random_tensor.clip(0.3,0.6)

tensor([[0.3000, 0.5109, 0.6000, 0.6000],
        [0.3917, 0.4209, 0.6000, 0.6000],
        [0.6000, 0.5648, 0.6000, 0.6000]])