In [1]:
import torch

In [2]:
x = torch.randn(5, requires_grad=True) # _pytorch creates computational graph 
x

tensor([ 0.0976,  0.2520,  2.0412, -1.0411,  0.4724], requires_grad=True)

In [3]:
y = x+2 # _check grad_fn value
print(y)

tensor([2.0976, 2.2520, 4.0412, 0.9589, 2.4724], grad_fn=<AddBackward0>)


In [4]:
z = y*y*2 # _check grad_fn value
print(z)

tensor([ 8.7998, 10.1433, 32.6624,  1.8391, 12.2257], grad_fn=<MulBackward0>)


In [5]:
z = z.mean() # _check grad_fn value
z

tensor(13.1340, grad_fn=<MeanBackward0>)

In [6]:
z.backward() # _backward can be applied only on scalar values and which has grad_fn
x.grad

tensor([1.6781, 1.8016, 3.2330, 0.7671, 1.9779])

In [7]:
weights = torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output = (weights*3).sum()
    model_output.backward()
    
    print(weights)
    print(weights.grad)
    print(model_output)
    
    weights.grad.zero_()
    print()
    

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)

tensor([1., 1., 1., 1.], requires_grad=True)
tensor([3., 3., 3., 3.])
tensor(12., grad_fn=<SumBackward0>)



In [9]:
w = torch.tensor([1],dtype= torch.float16,  requires_grad=True)
x = torch.tensor([1],dtype= torch.float16)
y = torch.tensor([2],dtype= torch.float16)

y_1 = w*x
s = (y_1 - y)

loss = s*s

In [11]:
loss.backward()

In [13]:
w.grad

tensor([-2.], dtype=torch.float16)