In [1]:
import torch

In [2]:
x = torch.empty(5)
x

tensor([-1.3186e-36,  4.5747e-41,  7.2868e-44,  0.0000e+00,  0.0000e+00])

In [3]:
random_tensor = torch.rand(2,3)
random_tensor

tensor([[0.3962, 0.2603, 0.5002],
        [0.2683, 0.1107, 0.7737]])

In [4]:
ones_t = torch.ones(1,2,3)
ones_t

tensor([[[1., 1., 1.],
         [1., 1., 1.]]])

In [5]:
x.dtype

torch.float32

In [6]:
ones_t = torch.ones(1,2,3, dtype=torch.int)
ones_t

tensor([[[1, 1, 1],
         [1, 1, 1]]], dtype=torch.int32)

In [8]:
random_tensor = torch.rand(2,3, dtype= torch.float16)
random_tensor

tensor([[0.4580, 0.3442, 0.8291],
        [0.3677, 0.9424, 0.1387]], dtype=torch.float16)

In [9]:
random_tensor.size()

torch.Size([2, 3])

In [10]:
torch.tensor([1,2,3,4,5,6])

tensor([1, 2, 3, 4, 5, 6])

In [11]:
x = torch.rand(3,3)
y = torch.rand(3,3)
z = x + y
z

tensor([[0.8631, 1.6362, 0.8443],
        [0.4687, 0.7700, 1.2469],
        [1.3643, 0.5742, 0.9817]])

In [12]:
y.add_(x) # _ underscore means inplace updation
y

tensor([[0.8631, 1.6362, 0.8443],
        [0.4687, 0.7700, 1.2469],
        [1.3643, 0.5742, 0.9817]])

In [13]:
t = torch.rand(4,6)
t[:, 1:4]

tensor([[4.7289e-01, 9.1171e-01, 9.0950e-02],
        [2.5424e-02, 4.8131e-01, 3.7432e-04],
        [6.0664e-02, 7.1672e-01, 5.5779e-01],
        [6.1256e-01, 2.3480e-01, 2.8664e-01]])

In [14]:
t = t.view(-1, 8) # -similar to reshape in numpy
t

tensor([[4.1154e-01, 4.7289e-01, 9.1171e-01, 9.0950e-02, 9.8452e-01, 3.4950e-01,
         5.1840e-01, 2.5424e-02],
        [4.8131e-01, 3.7432e-04, 4.4270e-01, 2.0669e-01, 9.1947e-01, 6.0664e-02,
         7.1672e-01, 5.5779e-01],
        [1.9964e-01, 8.5426e-02, 4.0117e-01, 6.1256e-01, 2.3480e-01, 2.8664e-01,
         4.5281e-02, 5.8796e-01]])