In [9]:
!pip install tensorflow-gpu

     |████████████████████████████████| 454.3MB 40kB/s 
     |████████████████████████████████| 4.0MB 46.3MB/s 
     |████████████████████████████████| 1.2MB 41.0MB/s 
     |████████████████████████████████| 4.0MB 31.6MB/s 
     |████████████████████████████████| 471kB 55.2MB/s 
     |████████████████████████████████| 6.0MB 21.6MB/s 
     |████████████████████████████████| 4.9MB 37.5MB/s 
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
  Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
  Found existing installation: gas

In [10]:
!nvidia-smi

Mon May 24 10:28:25 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   48C    P0    25W /  70W |    678MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T=8
D=2
M=3

In [3]:
X = np.random.randn(1, T, D)
X

array([[[ 1.30150429,  0.62055347],
        [-0.41430267, -0.42749328],
        [ 0.95439675, -0.37740886],
        [-0.85345109,  0.2869347 ],
        [ 0.89709121, -0.55839491],
        [ 0.18981262,  0.87226494],
        [ 0.24442701, -0.82467155],
        [-0.56332277, -0.88437738]]])

In [4]:
def lstm1():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.LSTM(M, return_state=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h} \n cell state: {c}')

def lstm2():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.LSTM(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h} \n cell state: {c}')

In [5]:
def bidirectional_lstm1():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(M, return_state=True))
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h1, c1, h2, c2 = model.predict(X)

  print(f'\n output: {o} \n hidden state: {h1} \n cell state: {c1}')
  print(f'\n hidden state 2: {h2} \n cell state 2: {c2}')

def bidirectional_lstm2():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(M, return_state=True, return_sequences=True))
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h1, c1, h2, c2 = model.predict(X)
  
  print(f'\n output: {o} \n hidden state: {h1} \n cell state: {c1}')
  print(f'\n hidden state 2: {h2} \n cell state 2: {c2}')

In [6]:
def gru1():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.GRU(M, return_state=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h}')

def gru2():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h}')

In [7]:
lstm1()
print()
lstm2()
print()
gru1()
print()
gru2()


 output: [[ 0.02754593 -0.05335955  0.20477402]] 
 hidden state: [[ 0.02754593 -0.05335955  0.20477402]] 
 cell state: [[ 0.05439813 -0.15342027  0.34444013]]


 output: [[[ 0.12495808  0.039902    0.09250789]
  [ 0.01501257  0.02763182  0.03787709]
  [-0.0909612   0.07950267  0.04357034]
  [-0.01188476  0.02607423  0.01057912]
  [-0.14708966  0.07920034  0.01455282]
  [ 0.03426748  0.02826627  0.08381077]
  [-0.11100549  0.05254125  0.02297385]
  [-0.15536936  0.03941378 -0.05597426]]] 
 hidden state: [[-0.15536936  0.03941378 -0.05597426]] 
 cell state: [[-0.36886662  0.09573478 -0.10095623]]


 output: [[ 0.0433556  -0.3700417  -0.11149804]] 
 hidden state: [[ 0.0433556  -0.3700417  -0.11149804]]


 output: [[[-0.01380029 -0.01328706  0.2431491 ]
  [ 0.03933402 -0.01044368 -0.02025416]
  [ 0.05107219  0.03710089  0.17684922]
  [ 0.00931722 -0.04101759 -0.04332976]
  [ 0.0400633   0.02980436  0.14693683]
  [-0.00677371 -0.04222825  0.1638351 ]
  [ 0.06291139  0.0311833   0.05488411]

In [8]:
print()
bidirectional_lstm1()
print()
bidirectional_lstm2()



 output: [[-0.10931506  0.14450428  0.11644644 -0.16370362  0.02043377 -0.11435619]] 
 hidden state: [[-0.10931506  0.14450428  0.11644644]] 
 cell state: [[-0.2009417   0.35007727  0.19907603]]

 hidden state 2: [[-0.16370362  0.02043377 -0.11435619]] 
 cell state 2: [[-0.55052924  0.03852355 -0.19328937]]


 output: [[[ 0.25339946  0.04262212  0.09905265 -0.09507814  0.08643603
    0.13840297]
  [ 0.09143157  0.02732537  0.04314755 -0.03787002  0.188876
   -0.0783005 ]
  [ 0.12932207  0.08639635  0.09415144 -0.09012374  0.15559752
   -0.00403696]
  [ 0.01273185 -0.11232392  0.00291162  0.00379805  0.09283872
   -0.0109753 ]
  [ 0.06635398  0.01906535  0.06670833 -0.11080563  0.16537863
    0.01277612]
  [ 0.15963684 -0.07807346  0.07727219 -0.04746553  0.03546294
    0.05627945]
  [ 0.08042548  0.03537903  0.03824256 -0.06608905  0.17924623
   -0.14359891]
  [-0.04057831  0.07222555 -0.10407761  0.00815827  0.09063606
   -0.08599688]]] 
 hidden state: [[-0.04057831  0.07222555 -0.1