In [1]:
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

In [2]:
T=8
D=2
M=3

In [6]:
X = np.random.randn(1, T, D)
X

array([[[ 0.1064096 ,  1.58960527],
        [ 0.97370068,  0.20258235],
        [ 1.23757792, -0.72061843],
        [ 1.69564744,  0.10761831],
        [-0.06240792,  0.66033281],
        [-0.14406551, -0.14251515],
        [-0.4205752 ,  0.19733169],
        [-1.17235025, -0.91646475]]])

In [11]:
def lstm1():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.LSTM(M, return_state=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h} \n cell state: {c}')

def lstm2():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.LSTM(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h, c = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h} \n cell state: {c}')

In [9]:
def gru1():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.GRU(M, return_state=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h}')

def gru2():

  input_ = tf.keras.Input(shape=(T, D))
  rnn = tf.keras.layers.GRU(M, return_state=True, return_sequences=True)
  x = rnn(input_)

  model = tf.keras.Model(inputs=input_, outputs=x)
  o, h = model.predict(X)
  print(f'\n output: {o} \n hidden state: {h}')

In [12]:
lstm1()
print()
lstm2()
print()
gru1()
print()
gru2()


 output: [[-0.04089801  0.0511228  -0.06536477]] 
 hidden state: [[-0.04089801  0.0511228  -0.06536477]] 
 cell state: [[-0.10081381  0.0770378  -0.11647668]]


 output: [[[-0.21077417 -0.00374496 -0.18461013]
  [-0.2071511  -0.18030667 -0.17805585]
  [-0.07792532 -0.32132316 -0.12504598]
  [-0.15552571 -0.45344105 -0.13648558]
  [-0.24431054 -0.19230084 -0.2641816 ]
  [-0.14913143 -0.13262443 -0.20833175]
  [-0.14574641 -0.02891706 -0.17252581]
  [ 0.04635446  0.07991847  0.01225348]]] 
 hidden state: [[0.04635446 0.07991847 0.01225348]] 
 cell state: [[0.10412998 0.22890729 0.01741502]]


 output: [[ 0.01225862 -0.01366939  0.13360819]] 
 hidden state: [[ 0.01225862 -0.01366939  0.13360819]]


 output: [[[ 0.21295407  0.28842866  0.09085738]
  [ 0.13635445  0.32102048 -0.14624181]
  [-0.04552693  0.22495528 -0.44006607]
  [ 0.17240448  0.30564508 -0.5186654 ]
  [ 0.21264446  0.21665278 -0.21912864]
  [ 0.08088146 -0.02828521 -0.10217682]
  [ 0.05941249 -0.07304575  0.06484315]
  [-0