<a href="https://colab.research.google.com/drive/17_55Z2ExOGN2Nz-1bPcu5JGgxTV1I3PH?usp=sharing" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a> 

1. Data Preprocessing


In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
print(tf.__version__)

2.4.0


In [3]:
df = pd.read_csv('Churn_Modelling.csv')
display(df)

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   RowNumber        10000 non-null  int64  
 1   CustomerId       10000 non-null  int64  
 2   Surname          10000 non-null  object 
 3   CreditScore      10000 non-null  int64  
 4   Geography        10000 non-null  object 
 5   Gender           10000 non-null  object 
 6   Age              10000 non-null  int64  
 7   Tenure           10000 non-null  int64  
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64  
 10  HasCrCard        10000 non-null  int64  
 11  IsActiveMember   10000 non-null  int64  
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64  
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [5]:
df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1, inplace=True)

In [6]:
X = df.iloc[:, :-1].values
y = df.Exited.values

print(f'shape of train data {X.shape}')
print(f'shape of test data {y.shape}')

shape of train data (10000, 10)
shape of test data (10000,)


In [13]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

pre_processors = [('label_encoder', OrdinalEncoder(), [2]),
                  ('onehot_encoder', OneHotEncoder(), [1])]

col_transformer = ColumnTransformer(transformers=pre_processors, remainder='passthrough')
X = col_transformer.fit_transform(X)
print(X)

[[0.0 0.0 1.0 ... 1 1 101348.88]
 [0.0 1.0 0.0 ... 0 1 112542.58]
 [0.0 0.0 1.0 ... 1 0 113931.57]
 ...
 [0.0 0.0 1.0 ... 0 1 42085.58]
 [1.0 1.0 0.0 ... 1 0 92888.52]
 [0.0 0.0 1.0 ... 1 0 38190.78]]


In [25]:
print(X[0])

[0.0 0.0 1.0 0.0 0.0 619 42 2 0.0 1 1 1 101348.88]


In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [15]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

2. Model Building

In [16]:
ann = tf.keras.models.Sequential()

In [17]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [18]:
ann.add(tf.keras.layers.Dense(6, activation='relu'))

In [21]:
ann.add(tf.keras.layers.Dense(1, activation='sigmoid'))

In [22]:
ann.compile(optimizer='adam', loss= 'binary_crossentropy', metrics=['accuracy'])

3. Model Training

In [23]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5327 - accuracy: 0.7931
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4661 - accuracy: 0.7961
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4398 - accuracy: 0.7972
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4343 - accuracy: 0.7930
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4197 - accuracy: 0.8168
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4186 - accuracy: 0.8187
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4144 - accuracy: 0.8259
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4054 - accuracy: 0.8300
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4070 - accuracy: 0.8303
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4010 - accura

4. Model Testing

In [24]:
ann.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (32, 6)                   84        
_________________________________________________________________
dense_1 (Dense)              (32, 6)                   42        
_________________________________________________________________
dense_4 (Dense)              (32, 1)                   7         
Total params: 133
Trainable params: 133
Non-trainable params: 0
_________________________________________________________________


In [31]:
ann.predict(scaler.transform([[0,0,1, 0, 1, 600, 40, 3, 60000, 2, 1, 1, 50000]]))

array([[0.7397977]], dtype=float32)

In [39]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred = y_pred.reshape(len(y_pred), 1)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score

con_matrix = confusion_matrix(y_test, y_pred)
print(con_matrix)

[[1524   71]
 [ 198  207]]


In [41]:
accuracy_score(y_pred, y_test)

0.8655